title: St. Petersburg-'s Best Real Estate Training
description: >-
  Leisa Erickson, a top Real Estate Agent in St. Petersburg, shares her own
  internal real estate agent training for free. Her Real Estate Training, Tips
  and Advice will help you sell more homes in less time.
CTAS:
  cta1: Join Our Team
  cta1_link: /join-our-team/
  cta2: Free Newsletter
  cta2_link: /subscribe/
  cta3: Free Strategy Call
  cta3_link: /strategy-call/
  cta4: Events
  cta4_link: /
show_custom_links: false
custom_links:
  - title:
    url:
client:
  name: Leisa Erickson
  title: Broker | License Partner | Private Office
  license_number:
  about_markdown: >-
    Premier real estate agents, the Leisa Erickson Group brings 20+ years of
    executive sales and marketing experience to your projects related to buying,
    selling, and investing in real estate. Our goal: to make sure that buyers
    get into the homes of their dreams, and that sellers gain unparalleled
    profits. The Team takes pride in serving as their client’s trusted adviser.
    You can depend on us to deliver the right deal at the right time for the
    right price - for you, your family, and your business.


    The Erickson Team's deep knowledge of the Tampa Bay/St. Petersburg real
    estate market, their insider status as a longtime real estate investors, and
    Leisa’s expertise as a noted sales and marketing expert offer clients a
    well-rounded perspective - and experience base - unique to other agents and
    in our area."Florida’s real estate market continues to accelerate and I’m
    excited about the opportunities for both buyers and sellers to capitalize on
    this rising tide. As an agent, I break the status quo and I market like a
    guerilla warrior to our database and within my network of agents we do
    business with locally. Our commitment is simple yet not routinely practiced
    in the business: We follow up and do what we say we’re going to do. We are
    an advocate for you, your money, and your investment. Anyone who’s ever
    worked with us can testify to our persistence and perseverance. You deserve
    nothing less!"
  brand: The Erickson Team
  brokerage: ENGEL & VÖLKERS ST. PETE
  market: St. Petersburg
  address: '102 2nd Ave NE, #101B St. Petersburg, FL 33701'
  phone: 239-789-7106
  phone_type:
  phone2:
  phone2_type:
  email: leisa.erickson@evrealestate.com
  url: https://leisaericksongroup.evrealestate.com/
forms:
  sitekey:
mission: >-
  Our Mission on this site is to educate Real Estate Agents on how to sell more
  homes.
socials:
  review_sm_icons: false
  facebook_url:
  linkedin_url:
  youtube_url:
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:
  google_business_url:
podcast:
  title: '-- market -- Real Estate Podcast with -- client name --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: >-
    Learn all the tips, tricks and more for buyers and sellers in the -- market
    -- Area Real Estate Market
  description: >-
    If you are looking to buy or sell a home, get all the information and the
    latest updates, tips, and tricks from -- client brand -- - your professional
    -- market -- Real Estate Agents.
  keywords: >-
    Real Estate for sale, Real Estate agents, top real estate agents, local real
    estate agents, find a real estate agent, houses for sale in -- market --,
    home selling tips, home for sale, home buying, home buying process, property
    finder, property search, property, real estate market, estate agent,
    realestate, real estate listings, buying a house, homes for sale, mls, home
    buyer
  author: '-- client name --'
images:
  client_headshot_path: /uploads/headshot.jpg
  hero_logo_path: /uploads/logo.png
  logo_width_number: 40
  hero_text: '-- market -- Real Estate Video Blog'
  hero_background_hex: '#999999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#b40101'
  theme_color: '#999'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'
navbar_colors:
  border_bottom:
header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent
buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: rgba(0, 0, 0, 0)
  secondary_button_text_color: '#ffffff'
